### ISSUE TITLE
OS?

### ISSUE THREAD

**Issue by marshalleq** [Amirrezahmi/SelfTalker#2]
Hi this looks amazing!  I noticed though that you don't say what OS you did this all on, I'm guessing linux of some description, so I'll try that first.  I've never used Jupyter before though, so perhaps it's multi OS.  Either way as a suggestion explaining this in the readme would be helpful.  Thanks.

**Comment by Amirrezahmi** [comment]
Hello. This is a Jupyter Notebook file, It's not OS-specific and can be run on any operating system that supports Python, including Windows, macOS, and Linux. By the way if you wanna convert this jupyter nb into web app with a UI, you can simply use `Anvil` . However please let me know if you had any other comments or issues. I'll add this thing in the readme too. Glad you liked it and thanks for your comment.

**Comment by Amirrezahmi** [comment]
Hello. This is a Jupyter Notebook file, It's not OS-specific and can be run on any operating system that supports Python, including Windows, macOS, and Linux. By the way if you wanna convert this jupyter nb into web app with a UI, you can simply use `Anvil` . However please let me know if you had any other comments or issues. I'll add this thing in the readme too. Glad you liked it and thanks for your comment.
